version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local
    networks:
      - local-dynamodb
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - 8000:8000

networks:
  local-dynamodb:
    name: local-dynamodb
